#!/usr/bin/env node
// Reads ../design.md frontmatter and emits src/styles/tokens.css.
// We parse the YAML frontmatter directly rather than depending on @google/design.md
// being installed; the design.md spec keeps tokens in YAML at the top of the file.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const DESIGN_MD = resolve(ROOT, "../design.md");
const OUT = resolve(ROOT, "src/styles/tokens.css");

function extractFrontmatter(src) {
  if (!src.startsWith("---")) throw new Error("design.md missing YAML frontmatter");
  const end = src.indexOf("\n---", 3);
  if (end === -1) throw new Error("design.md frontmatter not terminated");
  return src.slice(3, end).replace(/^\n/, "");
}

// Minimal YAML parser sufficient for design.md (indented maps, scalars, no arrays
// with complex nesting beyond what the file uses).
function parseYaml(yaml) {
  const lines = yaml.split("\n");
  const root = {};
  const stack = [{ indent: -1, node: root }];

  for (let raw of lines) {
    if (!raw.trim() || raw.trim().startsWith("#")) continue;
    const indent = raw.match(/^ */)[0].length;
    const line = raw.slice(indent);
    const m = line.match(/^([A-Za-z0-9_\-]+):\s*(.*)$/);
    if (!m) continue;
    const [, key, rest] = m;

    while (stack.length > 1 && stack[stack.length - 1].indent >= indent) stack.pop();
    const parent = stack[stack.length - 1].node;

    if (rest === "" || rest === undefined) {
      const child = {};
      parent[key] = child;
      stack.push({ indent, node: child });
    } else {
      let val = rest.trim();
      if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
        val = val.slice(1, -1);
      }
      parent[key] = val;
    }
  }
  return root;
}

const src = readFileSync(DESIGN_MD, "utf8");
const fm = extractFrontmatter(src);
const tokens = parseYaml(fm);

const colors = tokens.colors ?? {};
const typography = tokens.typography ?? {};
const spacing = tokens.spacing ?? {};
const rounded = tokens.rounded ?? {};

const cssVar = (name) => `--${name.replace(/[^a-zA-Z0-9_-]/g, "-")}`;

let css = "";
css += "/* Generated by scripts/build-tokens.mjs from ../design.md. Do not edit by hand. */\n\n";

// :root — base palette + light mode + spacing/rounded + typography refs
css += ":root {\n";
for (const [k, v] of Object.entries(colors)) css += `  ${cssVar(k)}: ${v};\n`;
for (const [k, v] of Object.entries(spacing)) css += `  ${cssVar("space-" + k)}: ${v};\n`;
for (const [k, v] of Object.entries(rounded)) css += `  ${cssVar("radius-" + k)}: ${v};\n`;
for (const [name, props] of Object.entries(typography)) {
  if (typeof props !== "object") continue;
  const prefix = `--font-${name}`;
  if (props.fontFamily) css += `  ${prefix}-family: ${props.fontFamily};\n`;
  if (props.fontSize) css += `  ${prefix}-size: ${props.fontSize};\n`;
  if (props.fontWeight) css += `  ${prefix}-weight: ${props.fontWeight};\n`;
  if (props.lineHeight) css += `  ${prefix}-line-height: ${props.lineHeight};\n`;
  if (props.letterSpacing) css += `  ${prefix}-letter-spacing: ${props.letterSpacing};\n`;
  if (props.textTransform) css += `  ${prefix}-text-transform: ${props.textTransform};\n`;
}
css += "}\n\n";

// Light mode (default surface = white, text = primary)
css += '[data-mode="light"] {\n';
css += "  --text: var(--primary);\n";
css += "  --card-bg: var(--primary);\n";
css += "  --card-text: var(--ink);\n";
css += "  --card-circle: var(--primary-soft);\n";
css += "  --card-clip-text: var(--primary);\n";
css += "  color-scheme: light;\n";
css += "}\n\n";

// Drenched mode (page is primary, text is white; cards invert)
css += '[data-mode="drenched"] {\n';
css += "  --surface: var(--primary);\n";
css += "  --text: var(--ink);\n";
css += "  --card-bg: var(--primary-soft);\n";
css += "  --card-text: var(--primary);\n";
css += "  --card-circle: var(--primary);\n";
css += "  --card-clip-text: var(--ink);\n";
css += "  color-scheme: dark;\n";
css += "}\n\n";

css += "body {\n  background-color: var(--surface);\n  color: var(--text);\n}\n";

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, css);

console.log(`build-tokens: wrote ${OUT}`);
